version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "authing-lambda-auth"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ua7bhp7hu2xf"
s3_prefix = "authing-lambda-auth"
region = "cn-north-1"
capabilities = "CAPABILITY_IAM"

